name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit_hash.outputs.commit_hash }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Get short commit hash
        id: commit_hash
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context:  .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wordpress:${{ env.COMMIT_HASH }}

  update-values:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout values repository
        uses: actions/checkout@v3
        with:
          repository: Ahmed-Hodhod/ABI_GitOps_K8S
          token:   ${{ secrets._GITHUB_TOKEN }}
          path: ABI_GitOps_K8S


      - name: Update values.yaml
        run: |
          sed -i 's/tag:.*/tag: ${{ needs.build.outputs.commit_hash }}/g' ABI_GitOps_K8S/app/values.yaml
          cat ABI_GitOps_K8S/app/values.yaml


      - name: Commit and push changes to helm application 
        run: |
          cd ABI_GitOps_K8S
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add app/values.yaml
          cat  app/values.yaml
          git commit -m "Update image tag to  ${{ needs.build.outputs.commit_hash }}"
          git push

      - name: Commit and push changes to kustomize applications 
        run: |
          cd ABI_GitOps_K8S
          
          # Set git configuration
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Update the image tag in both overlays
          sed -i "s|image: ahmedhodhod1/wordpress:.*|image: ahmedhodhod1/wordpress:${{ needs.build.outputs.commit_hash }}|g" overlays/prod/kustomization.yaml
          
          # Display changes for verification
          cat overlays/prod/kustomization.yaml
          
          # Commit and push changes
          git add overlays/prod/kustomization.yaml
          git commit -m "Update image tag to ${{ needs.build.outputs.commit_hash }}"
          git push



