name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get short commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context:  .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wordpress:${{ env.COMMIT_HASH }}

  update-values:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout values repository
        uses: actions/checkout@v3
        with:
          repository: github.com/Ahmed-Hodhod/ABI_GitOps_K8S
          token:   ${{ secrets._GITHUB_TOKEN }}
          path: ABI_GitOps_K8S

      - name: Update values.yaml
        run: |
          sed -i "s|image: .*|image: ${DOCKER_HUB_USERNAME}/wordpress:${{ env.COMMIT_HASH }}|" ABI_GitOps_K8S/app/values.yaml


      - name: Commit and push changes
        run: |
          cd values-repo
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ABI_GitOps_K8S/app/values.yaml
          git commit -m "Update image tag to ${{ env.COMMIT_HASH }}"
          git push
